name: "Sanctuary Core"
description: "A jump start for your Drupal Sanctuary project."
type: "Site"

install:
  - jsonapi
  - decoupled_router
  - jsonapi_menu_items
  - jsonapi_menu_items_hypermedia

config:
  actions:
    system.site:
      simple_config_update:
        page.front: "/home"
