name: "Sanctuary Core"
description: "A jump start for your Drupal Sanctuary project."
type: "Site"

install:
  - jsonapi
  - config_pages
  - decoupled_preview_iframe
  - decoupled_router
  - frontend_editing
  - jsonapi_menu_items
  - jsonapi_menu_items_hypermedia
  - jsonapi_views
  - iconify_icons
  - menu_item_extras
  - sanctuary

config:
  actions:
    # Set permissions for anonymous role.
    user.role.anonymous:
      ensure_exists:
        id: anonymous
      grantPermissions:
        - "view sanctuary_settings config page entity"
    system.theme:
      simple_config_update:
        default: "claro"
    frontend_editing.settings:
      simple_config_update:
        ui_toggle: false
        entity_types:
          config_pages:
            - sanctuary_settings
          node:
            - article
            - page
          menu_link_content:
            - main
            - social-links
