name: "Sanctuary Core"
description: "A jump start for your Drupal Sanctuary project."
type: "Site"

install:
  - jsonapi
  - config_pages
  - decoupled_router
  - jsonapi_menu_items
  - jsonapi_menu_items_hypermedia
  - iconify_icons
  - menu_item_extras
