redirect_anonymous: false
redirect_url: ""
preview_url: "http://localhost:4321"
preview_types:
  node:
    article: article
    page: page
route_sync: DECOUPLED_PREVIEW_IFRAME_ROUTE_SYNC
draft_provider: graphql_compose_preview
