entity_config:
  menu:
    account:
      enabled: false
    admin:
      enabled: false
    footer:
      enabled: false
    main:
      enabled: true
    social-links:
      enabled: false
    tools:
      enabled: false
  node:
    article:
      enabled: false
    page:
      enabled: false
  taxonomy_term:
    tags:
      enabled: false
field_config: {  }
settings:
  exclude_unpublished: true
  expose_entity_ids: true
  field_required_override: false
  schema_description: 'GraphQL Compose'
  schema_version: '1'
  simple_queries: true
  simple_unions: true
  site_name: false
  site_slogan: false
  site_front: true
  svg_image: false
  svg_filesize: 100
  inflector_langcode: en
  inflector_singularize: true
  edge_max_limit: 100
