entity_config:
  config_pages:
    sanctuary_settings:
      enabled: true
      query_load_enabled: true
      edges_enabled: true
  menu:
    account:
      enabled: false
    admin:
      enabled: false
    content:
      enabled: false
    footer:
      enabled: false
    main:
      enabled: true
    social-links:
      enabled: true
    tools:
      enabled: false
  node:
    article:
      enabled: false
    page:
      enabled: false
  taxonomy_term:
    tags:
      enabled: false
field_config:
  config_pages:
    sanctuary_settings:
      field_sanctuary_copyright:
        enabled: true
      field_sanctuary_site_description:
        enabled: true
      field_sanctuary_site_title:
        enabled: true
  menu_link_content:
    social-links:
      field_icon:
        enabled: true
settings:
  exclude_unpublished: true
  expose_entity_ids: true
  field_required_override: false
  schema_description: 'GraphQL Compose'
  schema_version: '1'
  simple_queries: true
  simple_unions: true
  site_name: false
  site_slogan: false
  site_front: true
  svg_image: false
  svg_filesize: 100
  inflector_langcode: en
  inflector_singularize: true
  edge_max_limit: 100
