name: "Sanctuary GraphQL"
description: "A jump start for your Drupal Sanctuary project using GraphQL."
type: "Site"
# Re-enable this dependency after initial development and/or create a dev recipe
# that can enable both.
# recipes:
#   - sanctuary_core

install:
  - graphql_compose
  - graphql_compose_edges
  - graphql_compose_menus
  - sanctuary_graphql
